Module8 task2
htmlacademy-yii/834029-task-force-1 pull request #18
Opened 2021-11-06 01:05 UTC by pasha-zigzag

2021-11-09 19:38 UTC, nkolosov commented on frontend/modules/api/controllers/MessagesController.php
> +            'task_id' => $task_id
Сразу в условии можно пропустить те, которые отправлены самим пользователем или уже прочитаны. Иначе каждый раз кол-во элементов в цикле будет увеличиваться.

Точно также, моэно вообще избавиться от этого цикла и делать просто один апдейт с нужным условием

2021-11-09 19:43 UTC, nkolosov requested changes

2021-11-09 19:43 UTC, nkolosov commented on frontend/modules/api/controllers/MessagesController.php
> +        $message->task_id = $requestParams['task_id'];
Тут стоит проверять, что такое задание есть

2021-11-09 19:43 UTC, nkolosov commented on frontend/modules/api/controllers/TasksController.php
> +                'new_messages' => function ($task) {
Аналогично, можно это сделать отдельным методом у задания (типа `$task->getNewMessages($user_id)`, который будет возвращать query, чтобы можно было вызвать `$task->getNewMessages()->count()`

2021-11-09 19:43 UTC, nkolosov commented on frontend/views/tasks/view.php
> +<script src="/js/messenger.js"></script>
Скрипты стоит подключать через ассеты, как стили и прочее

2021-11-10 13:57 UTC, pasha-zigzag commented on frontend/modules/api/controllers/MessagesController.php
> +            'task_id' => $task_id
не совсем понял - это метод для получения всех сообщений задания. И я перед тем как отдать этот массив помечаю все непрочитанные сообщения от собеседника как прочитанные. Вот только заметил, что нужно в проверку на 35 строке добавить !$message->is_read

2021-11-14 08:24 UTC, merged