Начал создавать класс Task
htmlacademy-yii/834029-task-force-1 pull request #2
Opened 2020-09-17 13:20 UTC by pasha-zigzag

2020-11-19 04:10 UTC, nkolosov requested changes

2020-11-19 04:10 UTC, nkolosov commented on classes/Task.php
> +                self::ACTION_RESPOND => ['next_status' => ''],
В этом массиве, кроме `next_status` других значений не планируется, так что проще не добавлять лишней вложенности, а сразу значением сделать следующий статус (а не массив с ключом `next_status`)

Далее, если статус после какого-то действия не меняется, то лучше не пустую строку делать в качестве значения, а `null`

2020-11-19 04:10 UTC, nkolosov commented on classes/Task.php
> +    const STATUS_NEW = 'new';
Для констант нужно указать модификатор доступа (`public`/`protected`/`private`)

2020-11-19 04:10 UTC, nkolosov commented on classes/Task.php
> +                self::ACTION_CANCEL => ['next_status' => self::STATUS_PERFORMED]
Кажется, что тут неверное действие

2020-11-19 04:10 UTC, nkolosov commented on classes/Task.php
> +    private $status_map = [
Данный массив не зависит от значений в классе, кажется, что его стоит сделать статической переменной (общей для всех объектов этого ккласса)

2020-11-19 04:10 UTC, nkolosov commented on classes/Task.php
> +            'title' => 'Новое',
Описание статусов стоит сделать аналогично описаниям действий, отдельным массивом

2020-11-19 04:10 UTC, nkolosov commented on classes/Task.php
> +    public function __construct($executor_id, $customer_id) {
Для всех аргументов всех функций и для возвращаемых значений стоит указывать тип (typehine)

2020-11-19 04:10 UTC, nkolosov commented on classes/Task.php
> +        $this->current_status = self::STATUS_NEW;
Значение по умолчанию лучше указать сразу в свойстве класса, а в конструкторе уже не трогать

2020-11-19 04:10 UTC, nkolosov commented on classes/Task.php
> +        $this->executor_id = $executor_id; //когда создается задание, исполнитель еще не выбран
Если `executor_id` может быть не указан, то это необязательный параметр, а необязательные параметры следуют после обязательных

2020-11-19 04:10 UTC, nkolosov commented on classes/Task.php
> +    public function getCurrentStatusMap() {
Название метода должно отражать, что он возвращает. Он возвращает строку (один элемент), а не map целиком

2020-11-19 04:10 UTC, nkolosov commented on classes/Task.php
> +    public function getNextStatus($action) {
Кажется, стоит роль пользователя тоже передавать в метод

2020-11-19 12:02 UTC, pasha-zigzag commented on classes/Task.php
> +                self::ACTION_CANCEL => ['next_status' => self::STATUS_PERFORMED]
Ну когда задание выполнено, заказчик же закрывает задание? У меня всего в карте 4 действия - Завершить, Откликнуться, Утвердить, Отказаться. Тут либо завершить, либо одобрить подойдет

2020-11-19 12:11 UTC, nkolosov commented on classes/Task.php
> +                self::ACTION_CANCEL => ['next_status' => self::STATUS_PERFORMED]
Да, это завершить. А `ACTION_CANCEL` -  это "отменить" и статус `cancelled` после него (в статусе `new`)

2020-11-19 13:18 UTC, pasha-zigzag commented on classes/Task.php
> +                self::ACTION_CANCEL => ['next_status' => self::STATUS_PERFORMED]
Тогда добавить действие complete и статус completed? )

2020-11-19 13:23 UTC, pasha-zigzag commented on classes/Task.php
> +    public function __construct($executor_id, $customer_id) {
а что конструктор возвращает? Нужно указывать?

2020-11-19 13:25 UTC, nkolosov commented on classes/Task.php
> +                self::ACTION_CANCEL => ['next_status' => self::STATUS_PERFORMED]
Ну, или так, или оставить статус как есть, а действие назвать "action_perform" например

2020-11-19 13:26 UTC, nkolosov commented on classes/Task.php
> +    public function __construct($executor_id, $customer_id) {
Конкретно для конструктора возвращаемое значение не указывается

2020-11-19 13:29 UTC, pasha-zigzag commented
Постарался всё учесть. Не знаю, приватными или публичными делать константы статусов и действий?

2020-11-19 13:32 UTC, nkolosov commented
Константы в данном случае лучше сделать публичными.

И роли пользователя возможные - тоже стоит сделать константами

2020-11-20 05:58 UTC, nkolosov requested changes

2020-11-20 05:58 UTC, nkolosov commented on classes/Task.php
> +        if($executor_id) {
`if` не нужен, значение по-умолчанию - `null`, в случае, если ничего не переданно - тоже будет `null`

2020-11-20 05:58 UTC, nkolosov commented on classes/Task.php
> +    public function getStatusMap(string $status): array {
Здесь стоит проверить, что `status` такой вообще существует (в списке констант).

Кроме того, методы, которые используют статические переменные (через `self`, а не `this`), стоит также объявить статическими (чтобы внешний код мог получить доступ к нему без создания объекта)

2020-11-20 05:58 UTC, nkolosov commented on classes/Task.php
> +        return self::$status_map[$this->current_status];
Лучше везде возвращать внутренний код статуса, а не его название на русском.

2020-11-20 05:58 UTC, nkolosov commented on classes/Task.php
> +    public function getStatusMap(string $status): array {
По-прежнему, метод называется `getStatusMap`, поэтому стоит возвращать именно `map`, а не конкретное значение в этой map

2020-11-20 05:58 UTC, nkolosov commented on classes/Task.php
> +        return $result;
Лучше возвращать код действия, а не значение на русском

2020-11-20 05:58 UTC, nkolosov commented on classes/Task.php
> +        return $this->getAvailableActions($status, self::EXECUTOR_ROLE);
Стоит проверить, что такой статус существует

2020-11-20 05:58 UTC, nkolosov commented on classes/Task.php
> +        return self::$status_action_map[$this->current_status][$role][$action] ?? '';
Стоит проверить, что такое действие и роль существуют

2020-11-20 05:58 UTC, nkolosov commented on classes/Task.php
> +        $this->current_status = $newStatus;
Стоит проверить, что такой статус существует

2020-11-20 06:18 UTC, pasha-zigzag commented on classes/Task.php
> +    public function getStatusMap(string $status): array {
так он же и возвращает массив. Например, для статуса `new` вернется 
```
        [
            self::EXECUTOR_ROLE => [
                self::ACTION_RESPOND => null,
                self::ACTION_REFUSE => null
            ],
            self::CUSTOMER_ROLE => [
                self::ACTION_CANCEL => self::STATUS_CANCELED,
                self::ACTION_APPROVE => self::STATUS_IN_WORK
            ]
        ]
```

2020-11-25 07:58 UTC, merged